package cn.yc.cms.dao.LoginDao;

import cn.yc.cms.pojo.Permissions;

public interface PermissionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_permissions
     *
     * @mbg.generated Sun Dec 23 00:45:39 CST 2018
     */
    int deleteByPrimaryKey(Integer pId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_permissions
     *
     * @mbg.generated Sun Dec 23 00:45:39 CST 2018
     */
    int insert(Permissions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_permissions
     *
     * @mbg.generated Sun Dec 23 00:45:39 CST 2018
     */
    int insertSelective(Permissions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_permissions
     *
     * @mbg.generated Sun Dec 23 00:45:39 CST 2018
     */
    Permissions selectByPrimaryKey(Integer pId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_permissions
     *
     * @mbg.generated Sun Dec 23 00:45:39 CST 2018
     */
    int updateByPrimaryKeySelective(Permissions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_permissions
     *
     * @mbg.generated Sun Dec 23 00:45:39 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(Permissions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_permissions
     *
     * @mbg.generated Sun Dec 23 00:45:39 CST 2018
     */
    int updateByPrimaryKey(Permissions record);
}