package cn.yc.cms.pojo;

import java.util.Date;

public class Admin {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_table.a_id
     *
     * @mbg.generated Sat Dec 22 23:36:04 CST 2018
     */
    private Integer aId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_table.a_name
     *
     * @mbg.generated Sat Dec 22 23:36:04 CST 2018
     */
    private String aName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_table.a_pwd
     *
     * @mbg.generated Sat Dec 22 23:36:04 CST 2018
     */
    private String aPwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_table.a_time
     *
     * @mbg.generated Sat Dec 22 23:36:04 CST 2018
     */
    private Date aTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_table.a_role
     *
     * @mbg.generated Sat Dec 22 23:36:04 CST 2018
     */
    private Integer aRole;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_table.a_id
     *
     * @return the value of admin_table.a_id
     *
     * @mbg.generated Sat Dec 22 23:36:04 CST 2018
     */
    public Integer getaId() {
        return aId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_table.a_id
     *
     * @param aId the value for admin_table.a_id
     *
     * @mbg.generated Sat Dec 22 23:36:04 CST 2018
     */
    public void setaId(Integer aId) {
        this.aId = aId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_table.a_name
     *
     * @return the value of admin_table.a_name
     *
     * @mbg.generated Sat Dec 22 23:36:04 CST 2018
     */
    public String getaName() {
        return aName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_table.a_name
     *
     * @param aName the value for admin_table.a_name
     *
     * @mbg.generated Sat Dec 22 23:36:04 CST 2018
     */
    public void setaName(String aName) {
        this.aName = aName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_table.a_pwd
     *
     * @return the value of admin_table.a_pwd
     *
     * @mbg.generated Sat Dec 22 23:36:04 CST 2018
     */
    public String getaPwd() {
        return aPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_table.a_pwd
     *
     * @param aPwd the value for admin_table.a_pwd
     *
     * @mbg.generated Sat Dec 22 23:36:04 CST 2018
     */
    public void setaPwd(String aPwd) {
        this.aPwd = aPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_table.a_time
     *
     * @return the value of admin_table.a_time
     *
     * @mbg.generated Sat Dec 22 23:36:04 CST 2018
     */
    public Date getaTime() {
        return aTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_table.a_time
     *
     * @param aTime the value for admin_table.a_time
     *
     * @mbg.generated Sat Dec 22 23:36:04 CST 2018
     */
    public void setaTime(Date aTime) {
        this.aTime = aTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_table.a_role
     *
     * @return the value of admin_table.a_role
     *
     * @mbg.generated Sat Dec 22 23:36:04 CST 2018
     */
    public Integer getaRole() {
        return aRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_table.a_role
     *
     * @param aRole the value for admin_table.a_role
     *
     * @mbg.generated Sat Dec 22 23:36:04 CST 2018
     */
    public void setaRole(Integer aRole) {
        this.aRole = aRole;
    }

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((aId == null) ? 0 : aId.hashCode());
		result = prime * result + ((aName == null) ? 0 : aName.hashCode());
		result = prime * result + ((aPwd == null) ? 0 : aPwd.hashCode());
		result = prime * result + ((aRole == null) ? 0 : aRole.hashCode());
		result = prime * result + ((aTime == null) ? 0 : aTime.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Admin other = (Admin) obj;
		if (aId == null) {
			if (other.aId != null)
				return false;
		} else if (!aId.equals(other.aId))
			return false;
		if (aName == null) {
			if (other.aName != null)
				return false;
		} else if (!aName.equals(other.aName))
			return false;
		if (aPwd == null) {
			if (other.aPwd != null)
				return false;
		} else if (!aPwd.equals(other.aPwd))
			return false;
		if (aRole == null) {
			if (other.aRole != null)
				return false;
		} else if (!aRole.equals(other.aRole))
			return false;
		if (aTime == null) {
			if (other.aTime != null)
				return false;
		} else if (!aTime.equals(other.aTime))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "Admin [aId=" + aId + ", aName=" + aName + ", aPwd=" + aPwd + ", aTime=" + aTime + ", aRole=" + aRole
				+ "]";
	}
    
}