package cn.yc.cms.pojo;

import java.util.Date;

public class OrderTable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_table.order_id
     *
     * @mbg.generated Tue Dec 25 14:55:17 CST 2018
     */
    private Integer orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_table.vip_id
     *
     * @mbg.generated Tue Dec 25 14:55:17 CST 2018
     */
    private Integer vipId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_table.order_number
     *
     * @mbg.generated Tue Dec 25 14:55:17 CST 2018
     */
    private String orderNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_table.order_consignee
     *
     * @mbg.generated Tue Dec 25 14:55:17 CST 2018
     */
    private String orderConsignee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_table.order_AllpayNumber
     *
     * @mbg.generated Tue Dec 25 14:55:17 CST 2018
     */
    private Integer orderAllpaynumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_table.order_paynumber
     *
     * @mbg.generated Tue Dec 25 14:55:17 CST 2018
     */
    private Integer orderPaynumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_table.order_orderstate
     *
     * @mbg.generated Tue Dec 25 14:55:17 CST 2018
     */
    private Integer orderOrderstate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_table.order_paystate
     *
     * @mbg.generated Tue Dec 25 14:55:17 CST 2018
     */
    private Integer orderPaystate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_table.order_gostate
     *
     * @mbg.generated Tue Dec 25 14:55:17 CST 2018
     */
    private Integer orderGostate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_table.order_payway
     *
     * @mbg.generated Tue Dec 25 14:55:17 CST 2018
     */
    private Integer orderPayway;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_table.order_distributionway
     *
     * @mbg.generated Tue Dec 25 14:55:17 CST 2018
     */
    private Integer orderDistributionway;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_table.order_time
     *
     * @mbg.generated Tue Dec 25 14:55:17 CST 2018
     */
    private Date orderTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_table.order_id
     *
     * @return the value of order_table.order_id
     *
     * @mbg.generated Tue Dec 25 14:55:17 CST 2018
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_table.order_id
     *
     * @param orderId the value for order_table.order_id
     *
     * @mbg.generated Tue Dec 25 14:55:17 CST 2018
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_table.vip_id
     *
     * @return the value of order_table.vip_id
     *
     * @mbg.generated Tue Dec 25 14:55:17 CST 2018
     */
    public Integer getVipId() {
        return vipId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_table.vip_id
     *
     * @param vipId the value for order_table.vip_id
     *
     * @mbg.generated Tue Dec 25 14:55:17 CST 2018
     */
    public void setVipId(Integer vipId) {
        this.vipId = vipId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_table.order_number
     *
     * @return the value of order_table.order_number
     *
     * @mbg.generated Tue Dec 25 14:55:17 CST 2018
     */
    public String getOrderNumber() {
        return orderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_table.order_number
     *
     * @param orderNumber the value for order_table.order_number
     *
     * @mbg.generated Tue Dec 25 14:55:17 CST 2018
     */
    public void setOrderNumber(String orderNumber) {
        this.orderNumber = orderNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_table.order_consignee
     *
     * @return the value of order_table.order_consignee
     *
     * @mbg.generated Tue Dec 25 14:55:17 CST 2018
     */
    public String getOrderConsignee() {
        return orderConsignee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_table.order_consignee
     *
     * @param orderConsignee the value for order_table.order_consignee
     *
     * @mbg.generated Tue Dec 25 14:55:17 CST 2018
     */
    public void setOrderConsignee(String orderConsignee) {
        this.orderConsignee = orderConsignee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_table.order_AllpayNumber
     *
     * @return the value of order_table.order_AllpayNumber
     *
     * @mbg.generated Tue Dec 25 14:55:17 CST 2018
     */
    public Integer getOrderAllpaynumber() {
        return orderAllpaynumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_table.order_AllpayNumber
     *
     * @param orderAllpaynumber the value for order_table.order_AllpayNumber
     *
     * @mbg.generated Tue Dec 25 14:55:17 CST 2018
     */
    public void setOrderAllpaynumber(Integer orderAllpaynumber) {
        this.orderAllpaynumber = orderAllpaynumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_table.order_paynumber
     *
     * @return the value of order_table.order_paynumber
     *
     * @mbg.generated Tue Dec 25 14:55:17 CST 2018
     */
    public Integer getOrderPaynumber() {
        return orderPaynumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_table.order_paynumber
     *
     * @param orderPaynumber the value for order_table.order_paynumber
     *
     * @mbg.generated Tue Dec 25 14:55:17 CST 2018
     */
    public void setOrderPaynumber(Integer orderPaynumber) {
        this.orderPaynumber = orderPaynumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_table.order_orderstate
     *
     * @return the value of order_table.order_orderstate
     *
     * @mbg.generated Tue Dec 25 14:55:17 CST 2018
     */
    public Integer getOrderOrderstate() {
        return orderOrderstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_table.order_orderstate
     *
     * @param orderOrderstate the value for order_table.order_orderstate
     *
     * @mbg.generated Tue Dec 25 14:55:17 CST 2018
     */
    public void setOrderOrderstate(Integer orderOrderstate) {
        this.orderOrderstate = orderOrderstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_table.order_paystate
     *
     * @return the value of order_table.order_paystate
     *
     * @mbg.generated Tue Dec 25 14:55:17 CST 2018
     */
    public Integer getOrderPaystate() {
        return orderPaystate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_table.order_paystate
     *
     * @param orderPaystate the value for order_table.order_paystate
     *
     * @mbg.generated Tue Dec 25 14:55:17 CST 2018
     */
    public void setOrderPaystate(Integer orderPaystate) {
        this.orderPaystate = orderPaystate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_table.order_gostate
     *
     * @return the value of order_table.order_gostate
     *
     * @mbg.generated Tue Dec 25 14:55:17 CST 2018
     */
    public Integer getOrderGostate() {
        return orderGostate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_table.order_gostate
     *
     * @param orderGostate the value for order_table.order_gostate
     *
     * @mbg.generated Tue Dec 25 14:55:17 CST 2018
     */
    public void setOrderGostate(Integer orderGostate) {
        this.orderGostate = orderGostate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_table.order_payway
     *
     * @return the value of order_table.order_payway
     *
     * @mbg.generated Tue Dec 25 14:55:17 CST 2018
     */
    public Integer getOrderPayway() {
        return orderPayway;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_table.order_payway
     *
     * @param orderPayway the value for order_table.order_payway
     *
     * @mbg.generated Tue Dec 25 14:55:17 CST 2018
     */
    public void setOrderPayway(Integer orderPayway) {
        this.orderPayway = orderPayway;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_table.order_distributionway
     *
     * @return the value of order_table.order_distributionway
     *
     * @mbg.generated Tue Dec 25 14:55:17 CST 2018
     */
    public Integer getOrderDistributionway() {
        return orderDistributionway;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_table.order_distributionway
     *
     * @param orderDistributionway the value for order_table.order_distributionway
     *
     * @mbg.generated Tue Dec 25 14:55:17 CST 2018
     */
    public void setOrderDistributionway(Integer orderDistributionway) {
        this.orderDistributionway = orderDistributionway;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_table.order_time
     *
     * @return the value of order_table.order_time
     *
     * @mbg.generated Tue Dec 25 14:55:17 CST 2018
     */
    public Date getOrderTime() {
        return orderTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_table.order_time
     *
     * @param orderTime the value for order_table.order_time
     *
     * @mbg.generated Tue Dec 25 14:55:17 CST 2018
     */
    public void setOrderTime(Date orderTime) {
        this.orderTime = orderTime;
    }

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((orderAllpaynumber == null) ? 0 : orderAllpaynumber.hashCode());
		result = prime * result + ((orderConsignee == null) ? 0 : orderConsignee.hashCode());
		result = prime * result + ((orderDistributionway == null) ? 0 : orderDistributionway.hashCode());
		result = prime * result + ((orderGostate == null) ? 0 : orderGostate.hashCode());
		result = prime * result + ((orderId == null) ? 0 : orderId.hashCode());
		result = prime * result + ((orderNumber == null) ? 0 : orderNumber.hashCode());
		result = prime * result + ((orderOrderstate == null) ? 0 : orderOrderstate.hashCode());
		result = prime * result + ((orderPaynumber == null) ? 0 : orderPaynumber.hashCode());
		result = prime * result + ((orderPaystate == null) ? 0 : orderPaystate.hashCode());
		result = prime * result + ((orderPayway == null) ? 0 : orderPayway.hashCode());
		result = prime * result + ((orderTime == null) ? 0 : orderTime.hashCode());
		result = prime * result + ((vipId == null) ? 0 : vipId.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		OrderTable other = (OrderTable) obj;
		if (orderAllpaynumber == null) {
			if (other.orderAllpaynumber != null)
				return false;
		} else if (!orderAllpaynumber.equals(other.orderAllpaynumber))
			return false;
		if (orderConsignee == null) {
			if (other.orderConsignee != null)
				return false;
		} else if (!orderConsignee.equals(other.orderConsignee))
			return false;
		if (orderDistributionway == null) {
			if (other.orderDistributionway != null)
				return false;
		} else if (!orderDistributionway.equals(other.orderDistributionway))
			return false;
		if (orderGostate == null) {
			if (other.orderGostate != null)
				return false;
		} else if (!orderGostate.equals(other.orderGostate))
			return false;
		if (orderId == null) {
			if (other.orderId != null)
				return false;
		} else if (!orderId.equals(other.orderId))
			return false;
		if (orderNumber == null) {
			if (other.orderNumber != null)
				return false;
		} else if (!orderNumber.equals(other.orderNumber))
			return false;
		if (orderOrderstate == null) {
			if (other.orderOrderstate != null)
				return false;
		} else if (!orderOrderstate.equals(other.orderOrderstate))
			return false;
		if (orderPaynumber == null) {
			if (other.orderPaynumber != null)
				return false;
		} else if (!orderPaynumber.equals(other.orderPaynumber))
			return false;
		if (orderPaystate == null) {
			if (other.orderPaystate != null)
				return false;
		} else if (!orderPaystate.equals(other.orderPaystate))
			return false;
		if (orderPayway == null) {
			if (other.orderPayway != null)
				return false;
		} else if (!orderPayway.equals(other.orderPayway))
			return false;
		if (orderTime == null) {
			if (other.orderTime != null)
				return false;
		} else if (!orderTime.equals(other.orderTime))
			return false;
		if (vipId == null) {
			if (other.vipId != null)
				return false;
		} else if (!vipId.equals(other.vipId))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "OrderTable [orderId=" + orderId + ", vipId=" + vipId + ", orderNumber=" + orderNumber
				+ ", orderConsignee=" + orderConsignee + ", orderAllpaynumber=" + orderAllpaynumber
				+ ", orderPaynumber=" + orderPaynumber + ", orderOrderstate=" + orderOrderstate + ", orderPaystate="
				+ orderPaystate + ", orderGostate=" + orderGostate + ", orderPayway=" + orderPayway
				+ ", orderDistributionway=" + orderDistributionway + ", orderTime=" + orderTime + "]";
	}
    
}