package cn.yc.cms.pojo;

public class Permissions {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_permissions.p_id
     *
     * @mbg.generated Sun Dec 23 00:45:39 CST 2018
     */
    private Integer pId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_permissions.p_name
     *
     * @mbg.generated Sun Dec 23 00:45:39 CST 2018
     */
    private String pName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_permissions.p_level
     *
     * @mbg.generated Sun Dec 23 00:45:39 CST 2018
     */
    private Integer pLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_permissions.p_controller
     *
     * @mbg.generated Sun Dec 23 00:45:39 CST 2018
     */
    private String pController;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_permissions.p_id
     *
     * @return the value of admin_permissions.p_id
     *
     * @mbg.generated Sun Dec 23 00:45:39 CST 2018
     */
    public Integer getpId() {
        return pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_permissions.p_id
     *
     * @param pId the value for admin_permissions.p_id
     *
     * @mbg.generated Sun Dec 23 00:45:39 CST 2018
     */
    public void setpId(Integer pId) {
        this.pId = pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_permissions.p_name
     *
     * @return the value of admin_permissions.p_name
     *
     * @mbg.generated Sun Dec 23 00:45:39 CST 2018
     */
    public String getpName() {
        return pName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_permissions.p_name
     *
     * @param pName the value for admin_permissions.p_name
     *
     * @mbg.generated Sun Dec 23 00:45:39 CST 2018
     */
    public void setpName(String pName) {
        this.pName = pName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_permissions.p_level
     *
     * @return the value of admin_permissions.p_level
     *
     * @mbg.generated Sun Dec 23 00:45:39 CST 2018
     */
    public Integer getpLevel() {
        return pLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_permissions.p_level
     *
     * @param pLevel the value for admin_permissions.p_level
     *
     * @mbg.generated Sun Dec 23 00:45:39 CST 2018
     */
    public void setpLevel(Integer pLevel) {
        this.pLevel = pLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin_permissions.p_controller
     *
     * @return the value of admin_permissions.p_controller
     *
     * @mbg.generated Sun Dec 23 00:45:39 CST 2018
     */
    public String getpController() {
        return pController;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin_permissions.p_controller
     *
     * @param pController the value for admin_permissions.p_controller
     *
     * @mbg.generated Sun Dec 23 00:45:39 CST 2018
     */
    public void setpController(String pController) {
        this.pController = pController;
    }

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((pController == null) ? 0 : pController.hashCode());
		result = prime * result + ((pId == null) ? 0 : pId.hashCode());
		result = prime * result + ((pLevel == null) ? 0 : pLevel.hashCode());
		result = prime * result + ((pName == null) ? 0 : pName.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Permissions other = (Permissions) obj;
		if (pController == null) {
			if (other.pController != null)
				return false;
		} else if (!pController.equals(other.pController))
			return false;
		if (pId == null) {
			if (other.pId != null)
				return false;
		} else if (!pId.equals(other.pId))
			return false;
		if (pLevel == null) {
			if (other.pLevel != null)
				return false;
		} else if (!pLevel.equals(other.pLevel))
			return false;
		if (pName == null) {
			if (other.pName != null)
				return false;
		} else if (!pName.equals(other.pName))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "Permissions [pId=" + pId + ", pName=" + pName + ", pLevel=" + pLevel + ", pController=" + pController
				+ "]";
	}
    
}