package cn.yc.cms.pojo;

public class Role {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_table.r_id
     *
     * @mbg.generated Sat Dec 22 23:05:30 CST 2018
     */
    private Integer rId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_table.r_name
     *
     * @mbg.generated Sat Dec 22 23:05:30 CST 2018
     */
    private String rName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role_table.r_perm
     *
     * @mbg.generated Sat Dec 22 23:05:30 CST 2018
     */
    private Integer rPerm;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_table.r_id
     *
     * @return the value of role_table.r_id
     *
     * @mbg.generated Sat Dec 22 23:05:30 CST 2018
     */
    public Integer getrId() {
        return rId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_table.r_id
     *
     * @param rId the value for role_table.r_id
     *
     * @mbg.generated Sat Dec 22 23:05:30 CST 2018
     */
    public void setrId(Integer rId) {
        this.rId = rId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_table.r_name
     *
     * @return the value of role_table.r_name
     *
     * @mbg.generated Sat Dec 22 23:05:30 CST 2018
     */
    public String getrName() {
        return rName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_table.r_name
     *
     * @param rName the value for role_table.r_name
     *
     * @mbg.generated Sat Dec 22 23:05:30 CST 2018
     */
    public void setrName(String rName) {
        this.rName = rName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role_table.r_perm
     *
     * @return the value of role_table.r_perm
     *
     * @mbg.generated Sat Dec 22 23:05:30 CST 2018
     */
    public Integer getrPerm() {
        return rPerm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role_table.r_perm
     *
     * @param rPerm the value for role_table.r_perm
     *
     * @mbg.generated Sat Dec 22 23:05:30 CST 2018
     */
    public void setrPerm(Integer rPerm) {
        this.rPerm = rPerm;
    }

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((rId == null) ? 0 : rId.hashCode());
		result = prime * result + ((rName == null) ? 0 : rName.hashCode());
		result = prime * result + ((rPerm == null) ? 0 : rPerm.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Role other = (Role) obj;
		if (rId == null) {
			if (other.rId != null)
				return false;
		} else if (!rId.equals(other.rId))
			return false;
		if (rName == null) {
			if (other.rName != null)
				return false;
		} else if (!rName.equals(other.rName))
			return false;
		if (rPerm == null) {
			if (other.rPerm != null)
				return false;
		} else if (!rPerm.equals(other.rPerm))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "Role [rId=" + rId + ", rName=" + rName + ", rPerm=" + rPerm + "]";
	}
    
}